version: '3.8'

services:
  # --- СЕРВИС 1: БАЗА ДАННЫХ ---
  db:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Пароль рута (берем из .env)
      MYSQL_DATABASE: ${DB_NAME}           # Имя базы, создастся автоматически
      MYSQL_USER: ${DB_USER}               # Пользователь
      MYSQL_PASSWORD: ${DB_PASSWORD}       # Пароль пользователя
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- СЕРВИС 2: ВАШ БОТ ---
  service_bot:
    build: .
    container_name: service_bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy 
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - .:/app

volumes:
  db_data: